### ISSUE TITLE
Order created with different range amount that specified

### ISSUE THREAD

**Issue by zx9r** [Reckless-Satoshi/robosats#112]
**Describe the bug**
I have created a sell order with range amount 50-125 EUR, however the published order has a range of 50-130

**To Reproduce**
I guess just creating an order with said parameters, didnt try repeating though

**Expected behavior**
Published order should have the amount range specified by the user

**Screenshots**
In the following screenshot the range 50-130 can be seen:

![image](https://user-images.githubusercontent.com/20980128/165616319-4c462b15-c988-4eb5-a31d-baded005c0f8.png)

However, the range was created as 50-125, as can be seen in the following screenshot from the invoice memo:

![image](https://user-images.githubusercontent.com/20980128/165618048-fb8c88dd-208d-4c05-9de8-453f8c1fb889.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Tor Browser
 - Version: 11.0.10 (based on Mozilla Firefox 91.8.0esr) (64-bit)

**Comment by Reckless-Satoshi** [comment]
Thanks for reporting @MishoKanaria !

Seems to be a rounding issue on the front end (it rounds to precision of two digits). 
https://github.com/Reckless-Satoshi/robosats/blob/ba9bc16b531b86f8448cdae1308c57e84cb391eb/frontend/src/components/OrderPage.js#L535
Yet the order is exactly 50-125 (the description of the invoice is always right).

The precision is set to only 2 since this the max precision allowed by the Make Order slider. However, we then introduced the textfield that allows users to input any arbitrary number. So I assume you entered the 125 manually on the textfield.

Easy fix, let's increase precision in the order details page :)

**Comment by zx9r** [comment]
Yep, I dont remember If I entered the 125 manually but I guess you are right

BTW, who is MishoKanaria ? ;)

**Comment by Reckless-Satoshi** [comment]
> BTW, who is MishoKanaria ? ;)

Wops! :D The automatic recommended @tag played with me ;)
