### ISSUE TITLE
Unclear flow for the seller taker

### ISSUE THREAD

**Issue by rkfg** [Reckless-Satoshi/robosats#137]
**Is your feature request related to a problem? Please describe.**
Turns out it's not very clear for the sat seller that takes a buy order that they should send sats _twice_, first the bond and then the actual order amount. Because of that they can lose the bond after timeout. This happened to my counterparty (I was the buyer and the seller lost their bond).

**Describe the solution you'd like**
I've never sold sats so I don't really know what the seller flow looks like 😅 But I guess it should be explicitly said that the bond has been accepted, the deal is locked and now it's time to post the bigger amount + mention that unless *you*, the seller, don't do it in 3 hours you will lose the bond. It must be clear that the deal is on pause currently because *you* (and not the buyer!) should do something, otherwise you'll be at a loss.

**Comment by Reckless-Satoshi** [comment]
I had not thought about this. But indeed I can see there could potentially, _for a very unaware seller_, some confusion.

What do you propose as a fix? Currently the Contract Box will explicitly ask "Deposit the Escrow" with a full size QR code, it shows a new trading step (2/4 instead of 1/4) and the message is colored in green (unlike any other bond). The only way I understand this could be more obvious is to use a more jarring color... "red"?

**Comment by rkfg** [comment]
I suppose it might be confusing to people who use the platform for the first time. Maybe it's unclear how "bond" is different from "escrow", to me these words are pretty similar so the seller might have thought it's kind of the same thing they'd already done. I suppose rewording should help + if there's no explicit information that the seller will lose the bond if they don't deposit in 3 hours I propose to add and highlight it.

**Comment by Reckless-Satoshi** [comment]
@rkfg Fixed in https://github.com/Reckless-Satoshi/robosats/commit/1a751b4fa7ae77e15b06e9131133950652d1e728
Will be live in the next platform update later this week. Closing this Issue.
