### ISSUE TITLE
Attempting Lightning Payment stuck

### ISSUE THREAD

**Issue by RedNumber1** [Reckless-Satoshi/robosats#145]
I had to leave to make inbound liquidity and now its stuck on "RoboSats is trying to pay your lightning invoice. Remember that lightning nodes must be online in order to receive payments." No retrying

**Comment by Reckless-Satoshi** [comment]
Hey @RedNumber1,

> I had to leave to make inbound liquidity and now its stuck on "RoboSats is trying to pay your lightning invoice. Remember that lightning nodes must be online in order to receive payments." No retrying

One payment was 'holded' by one routing node, probably a crash or shut down somewhere in the network. Any payment after it entered a queue in RoboSats end, so that's why they show as "Attempting (...)" but it does not seem to ever finish. After restarting LND payments should have succeeded/failed as expected. Except the one related to order #4701 that is still in hold due to the shut down in the route.

Sorry for the confusion. probably wording around these messages have to be improved, and the queuing after an stuck payment has to be parallelized. Not directly related to the development of the platform or bugs. So will close. For these matters is better to use the community group in Telegram or email to robosats.
