### ISSUE TITLE
Copy button in the Profile Dialog does not work on Tor

### ISSUE THREAD

**Issue by stakingpoolspace** [Reckless-Satoshi/robosats#227]
**Description**
After starting a session on Tor and opening the Profile Dialog (bottom-left corner), the copy button (to copy the token) does not work. While the copy button on the home screen (UserGenPage) _does work_ on Tor.

When I run the frontend locally (in an attempt to fix the issue), the copy button in the Profile Dialog does work.

**To Reproduce**
1. Go to http://robosats6tkf3eva7x2voqso3a5wcorsnw34jveyxfqi2fu7oyheasid.onion
2. Click on the profile in the bottom-left corner
3. Click on the copy button
4. Paste somewhere and see that the token was not copied

**Desktop:**
 - Windows 10
 - Brave Browser (Private Window with Tor)
 - Version 1.43.89

**Comment by Reckless-Satoshi** [comment]
Interesting. Indeed, I can replicate this behavior, but only in Brave w/ Tor on Windows.

Long story short, browsers do not want to allow you to copy from insecure contexts (HTTP instead of HTTPS). Since TOR browser is thought for .onion (most being HTTP), there is usually no problem with copying to clipboard, as it considers these contexts as secure. However, any other browser simply won't allow you to copy at all. This was true until we implemented a trick:
https://github.com/Reckless-Satoshi/robosats/blob/425225d23d0618f0e49d7268adeedcba091bd289/frontend/src/utils/clipboard.js#L1-L24
If the context is insecure, it tries to do a weird trick (I don't even understand it). It seems this trick does not work if the copy button is placed on the Profile Dialog (maybe it cannot move the text area out of the viewport?). I would guess it does not work on any Dialog. 

Probably there is nothing we can do about this.

**Comment by stakingpoolspace** [comment]
Thanks for the quick reply! After some playing around with the clipboard.js code, I might have found a solution. I have commented out the if/else statement to only work with the code in the else statement. Without my changes the copy button in the Profile Dialog does not work, but with a few additions it does work:

```javascript
export function copyToClipboard(textToCopy) {
// navigator clipboard api needs a secure context (https)
// this function attempts to copy also on http contexts
// useful on the http i2p site and on torified browsers
// if (navigator.clipboard && window.isSecureContext) {
//     // navigator clipboard api method'
//     return navigator.clipboard.writeText(textToCopy);
// } else {
    // text area method
    let textArea = document.createElement("textarea");
    textArea.value = textToCopy;
    textArea.id = "textToCopy"
    // make the textarea out of viewport
    textArea.style.position = "fixed";
    textArea.style.left = "-999999px";
    textArea.style.top = "-999999px";
    document.body.appendChild(textArea);
    textArea.focus();
    textArea.select();
    document.getElementById("textToCopy").focus();
    document.getElementById("textToCopy").select();
    return new Promise((res, rej) => {
        // here the magic happens
        document.execCommand('copy') ? res() : rej();
        textArea.remove();
    });
// }
}
```

I'm not sure why, but the code needs both the
```javascript
textArea.focus();
textArea.select();
```
and
```javascript
document.getElementById("textToCopy").focus();
document.getElementById("textToCopy").select();
```
to work in the Profile Dialog.
