### ISSUE TITLE
Payment methods not showing full list

### ISSUE THREAD

**Issue by sahilc0** [Reckless-Satoshi/robosats#337]
When creating a Buy order, the payment list is not showing all options. For example, Venmo is not on the list, and I have to manually type it for it to appear.

<img width="375" alt="CleanShot 2023-01-01 at 15 33 42@2x" src="https://user-images.githubusercontent.com/8256062/210185209-dfee81cd-3506-4d0a-823e-00003980000c.png">
<img width="308" alt="CleanShot 2023-01-01 at 15 35 14@2x" src="https://user-images.githubusercontent.com/8256062/210185215-dec4ee9b-7e0c-459e-b661-a3537828e283.png">

**Expected behavior**
Show full list of options available to user

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Brave

**Comment by Reckless-Satoshi** [comment]
This is the expected behavior. The list of available payment methods is very long (getting longer), therefore the payment methods will only display as you type (only the top 10 display by default). If every payment method was shown at once many icons would load at once potentially affecting performance in some devices.
